import React, { useState } from 'react';
import { addStyles, EditableMathField } from 'react-mathquill';
import { parse } from 'mathjs';
import {setFunctionInput} from '/Users/owenturnbull/ferd-math/ferd-math/src/main-elements/Sketch.js';
import mySketch from '/Users/owenturnbull/ferd-math/ferd-math/src/main-elements/Sketch.js';
import { importFunction } from "./Solve";

// inserts the required css to the <head> block.
// you can skip this, if you want to do that by yourself.
addStyles()


//GENERATED BY GPT
function Input() {
  const [input, setInput] = useState([]);
  const [steps, setSteps] = useState([]);

  const handleInputChange = (event) => {
    setInput(event.target.value);
  };

  const handleButtonClick = () => {
    const newSteps = importFunction(input);
    setSteps(newSteps);
  };

  return (
    <div>
      <input
        className="input-field"
        id="input-field"
        value={input}
        onChange={handleInputChange}
      />
      <button className="enter-button" onClick={handleButtonClick}>
        Enter
      </button>
      <Answer className="answer" steps={steps}/>
    </div>
  );
}

const Answer = (props) => {
  return (
    <div>
        {props.steps.map((step, index) => (
            <p className ='answer' key={index}>{step}</p>
        ))}
    </div>
  )
}

export default Input;